### ISSUE TITLE
Bluebird warning when using with NODE_ENV='development'

### ISSUE THREAD

**Issue by vjancik** [urish/firebase-server#47] opened 2016-05-07 20:40 UTC
```
Warning: a promise was created in a handler but was not returned from it
    at new A (eval at <anonymous> (/.../node_modules/firebase-server/node_modules/firebase-copy/index.js:7:14), <anonymous>:31:1337)
    at X.set (eval at <anonymous> (/.../node_modules/firebase-server/node_modules/firebase-copy/index.js:7:14), <anonymous>:259:322)
    at /.../node_modules/firebase-server/index.js:227:11
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at handleSet (/.../node_modules/firebase-server/index.js:226:13)
    at Object.<anonymous> (/.../node_modules/firebase-server/index.js:289:6)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/.../node_modules/firebase-server/node_modules/ws/lib/WebSocket.js:816:10)
    at /.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:364:5)
    at /.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (/.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:482:12)
    at Receiver.<anonymous> (/.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:451:33)
    at Receiver.add (/.../node_modules/firebase-server/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/.../node_modules/firebase-server/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

Is this a mistake in the project?

**Comment by urish** [comment] 2016-05-08 07:20
I have no idea - it seems to be coming from somewhere within the Firebase library itself. Can you try running the tests for firebase-server on your machine and see if you get the same message?

**Comment by vjancik** [comment] 2016-05-08 07:45
it seems I don't

**Comment by urish** [comment] 2016-05-08 07:56
I see. Well, since it is just a warning and it doesn't seem to reproduce on tests I think we will close it for now. If you manage to create a test cases that reproduces it or discover how to fix it, please let me know and we will look into it again...

**Closed by urish** 2016-05-08 07:56 UTC
